# Generated by Django 5.0.3 on 2024-04-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My new blog', max_length=50)),
                ('body', models.TextField(default='Lorem ipsum dolor sit, amet consectetur adipisicing elit. Explicabo esse quas rerum repellat hic eum? Provident id fugit dolorum possimus!')),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
